### ISSUE TITLE
verified artist not showing in profile

### ISSUE THREAD

**Issue by leetebbs** [eik-1/dbeats#14]
I have a verified artist address 
0x6898327521Af2C66744a7E9A6D8D007B999e60e4
on the smart contract but the dapp is asking for it to apply for artist

![Capture](https://github.com/user-attachments/assets/d950a0b4-70a2-412a-ae5f-d3265f1fa0ae)

**Comment by eik-1** [comment]
I think you have verified the artist first without him registering
FIrst teh artist should create a profile and then apply
