### ISSUE TITLE
Add roles to artistNFT.sol

### ISSUE THREAD

**Issue by leetebbs** [eik-1/dbeats#3]
Add roles to the artistNFT to allow multiple admins to mint this nft to artists. atm it only allows the contract owner.
https://github.com/eik-1/dbeats/blob/main/dbeats-contracts/contracts/ArtistNFT.sol

**Comment by eik-1** [comment]
Added functionality so that we can easily grant ARTIST_ROLE and mint the ArtistNFT to an address
